### ISSUE TITLE
ReferenceError: defer is not defined

### ISSUE THREAD

**Issue by hasssan** [vergara/indexeddb-promised#1]
hi, there are error in [add method ](https://github.com/vergara/indexeddb-promised/blob/master/js/indexeddb-promised.js#L105)
```
    transaction.onerror = function(event) {
      defer.reject(event.target.errorCode);
    };
```

**Comment by vergara** [comment]
Hi Hassan,

Thank you for reporting.

Can you please post here code reproducing the failure and specify the browser you used?

**Comment by hasssan** [comment]
I used it with React, Webpack and Babel for transpiler, browser chrome Version 43.0.2357.132 (64-bit).

my db.js files
```
let Builder = require('babel!indexeddb-promised');

let builder = new Builder('movie')
  .setVersion(2)
  .addObjectStore(
    {
      name: 'movie',
      keyType: { keyPath: 'id', autoIncrement: true }
    }
  );

let db = builder.build();

export default db;
```

then my app.js try add existing id in db
```
import db from './utils/db';

let movie = db.movie;

movie.add({
  id: 7,
  name: 'new movie'
}).then((result) => {
  console.log(result);
}).catch((error) => {
  console.log(error);
});
```
My expectation is get exception object in ``catch`` method. Instead I got this:

![selection_729](https://cloud.githubusercontent.com/assets/239714/8637601/b08ce74e-28c3-11e5-8abd-d8b102ef27b6.png)

tough is not real world case, but in my opinion worth checking

**Comment by vergara** [comment]
The issue has been fixed.
Thank you Hassan.
